---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "your-app-name.fullname" . }}
  labels:
    name: {{ include "your-app-name.name" . }}
    instance: {{ .Release.Name }}   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "your-app-name.name" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ include "your-app-name.name" . }}
        instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 5000
