---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "your-app-name.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "your-app-name.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
